### ISSUE TITLE
Colab pip install issue

### ISSUE THREAD

**Issue by robintzeng** [facebookresearch/videoseal#8]
Obtaining file:///content/videoseal/videoseal/videoseal
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by pierrefdz** [comment]
Sorry, i'll look into this now

**Comment by pierrefdz** [comment]
Loading should be ok now! There's an issue with RAM still, I'll try to do more next week.

**Comment by pierrefdz** [comment]
Should be working now!
Thanks for flagging
